name: andreaskiessling/form-dynamic-recipient
label: 'Form Dynamic Recipient'
priority: 100

prototypes:
  standard:
    formElementsDefinition:
      Form:
        renderingOptions:
          partialRootPaths:
            1517255631: 'EXT:form_dynamic_recipient/Resources/Private/Frontend/Partials/'

      FormDynamicRecipient:
        __inheritances:
          10: 'prototypes.standard.formElementsDefinition.SingleSelect'
        implementationClassName: 'AndreasKiessling\FormDynamicRecipient\Domain\Model\FormElements\SelectableRecipientOptions'
        renderingOptions:
          templateName: 'SingleSelect'

        formEditor:
          label: 'Selectable Recipient'
          groupSorting: 150
          properties:
            pageUid: ''
          predefinedDefaults:
            properties:
              pageUid: ''
              assignedVariable: 'dynamicRecipient'
          editors:
            300:
              identifier: 'pageUid'
              templateName: 'Inspector-Typo3WinBrowserEditor'
              label: 'formEditor.elements.FormDynamicRecipient.pageUid.label'
              fieldExplanationText: 'formEditor.elements.FormDynamicRecipient.pageUid.fieldExplanationText'
              buttonLabel: 'formEditor.elements.FormDynamicRecipient.pageUid.buttonLabel'
              browsableType: pages
              iconIdentifier: apps-pagetree-page-default
              propertyPath: 'properties.pageUid'
              propertyValidatorsMode: 'OR'
              propertyValidators:
                10: 'IntegerOrEmpty'
                20: 'FormElementIdentifierWithinCurlyBracesExclusive'

    formEditor:
      dynamicJavaScriptModules:
        additionalViewModelModules:
          1517255631: '@andreaskiessling/form-dynamic-recipient/Backend/FormEditor/ViewModel.js'
      translationFiles:
        1517255631: 'EXT:form_dynamic_recipient/Resources/Private/Language/Database.xlf'
